import { AntDesign, Feather, FontAwesome6, MaterialIcons } from '@expo/vector-icons';
import Entypo from '@expo/vector-icons/Entypo';
import FontAwesome5 from '@expo/vector-icons/FontAwesome5';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import Ionicons from '@expo/vector-icons/Ionicons';

export const  expenseCategories = [
  { name: 'Bills', icon: 'file-text', description: 'Regular payments', iconSet: Feather },
  { name: 'Food', icon: 'food', description: 'Groceries, restaurants, etc.', iconSet: MaterialCommunityIcons },
    { name: 'Transport', icon: 'car', description: 'Public transit, gas, parking', iconSet: FontAwesome5 },
    { name: 'Housing', icon: 'home', description: 'Rent, utilities, maintenance', iconSet: Entypo },
    { name: 'Entertainment', icon: 'tv', description: 'Movies, games, hobbies', iconSet: Entypo },
    { name: 'Shopping', icon: 'shopping-cart', description: 'Clothing, electronics, etc.', iconSet: Entypo },
    { name: 'Health', icon: 'medical', description: 'Doctor visits, medicine', iconSet: Ionicons },
    { name: 'Education', icon: 'graduation-cap', description: 'Tuition, books, courses', iconSet: FontAwesome5 },
    { name: 'Personal Care', icon: 'cut', description: 'Haircuts, cosmetics', iconSet: Ionicons },
    { name: 'Gifts', icon: 'gift', description: 'Presents, donations', iconSet: AntDesign },
    { name: 'Investments', icon: 'trending-up', description: 'Stocks, savings', iconSet: Feather },
    { name: 'Taxes', icon: 'calculator', description: 'Income tax, property tax', iconSet: Entypo },
    { name: 'Insurance', icon: 'shield', description: 'Health, car, home insurance', iconSet: Entypo },
    { name: 'Debt', icon: 'credit-card', description: 'Credit card, loan payments', iconSet: Entypo },
    { name: 'Travel', icon: 'aircraft', description: 'Vacations, business trips', iconSet: Entypo },
    { name: 'Pets', icon: 'baidu', description: 'Pet food, vet bills', iconSet: Entypo },
    { name: 'Fitness', icon: 'man', description: 'Gym membership, equipment', iconSet: Entypo },
    { name: 'Technology', icon: 'laptop', description: 'Software, gadgets', iconSet: Entypo },
    { name: 'Home Office', icon: 'briefcase', description: 'Office supplies, furniture', iconSet: Entypo },
    { name: 'Subscriptions', icon: 'newsletter', description: 'Streaming services, magazines', iconSet: Entypo },
    { name: 'Childcare', icon: 'baby', description: 'Daycare, babysitting', iconSet: FontAwesome5 },
    { name: 'Beauty', icon: 'star', description: 'Spa, beauty treatments', iconSet: Entypo },
    { name: 'Car Maintenance', icon: 'tools', description: 'Repairs, oil changes', iconSet: Entypo },
    { name: 'Home Decor', icon: 'light-up', description: 'Furniture, decorations', iconSet: Entypo },
    { name: 'Books', icon: 'book', description: 'Physical books, e-books', iconSet: Entypo },
    { name: 'Hobbies', icon: 'game-controller', description: 'Craft supplies, collectibles', iconSet: Entypo },
    { name: 'Charity', icon: 'heart', description: 'Donations, volunteering expenses', iconSet: Entypo },
    { name: 'Gardening', icon: 'flower', description: 'Plants, tools, supplies', iconSet: Entypo },
    { name: 'Laundry', icon: 'water', description: 'Dry cleaning, detergent', iconSet: Entypo },
    { name: 'Alcohol', icon: 'drink', description: 'Beer, wine, spirits', iconSet: Entypo },
    { name: 'Coffee', icon: 'cup', description: 'Cafe visits, home brewing', iconSet: Entypo },
    { name: 'Music', icon: 'note', description: 'Concerts, instruments, lessons', iconSet: Entypo },
    { name: 'Sports', icon: 'sports-club', description: 'Equipment, tickets', iconSet: Entypo },
    { name: 'Parking', icon: 'parking', description: 'Parking fees, permits', iconSet: FontAwesome5 },
    { name: 'Pharmacy', icon: 'lab-flask', description: 'Over-the-counter medicine', iconSet: Entypo },
    { name: 'Gifts Received', icon: 'box', description: 'Monetary gifts, vouchers', iconSet: Entypo },
    { name: 'Fines', icon: 'flag', description: 'Penalties, late fees', iconSet: Entypo },
    { name: 'Legal', icon: 'creative-commons-noderivs', description: 'Attorney fees, court costs', iconSet: Entypo },
    { name: 'Postage', icon: 'mail', description: 'Stamps, shipping', iconSet: Entypo },
    { name: 'Printing', icon: 'print', description: 'Document printing, photos', iconSet: Entypo },
    { name: 'Rental', icon: 'key', description: 'Equipment rentals, car rentals', iconSet: Entypo },
    { name: 'Repairs', icon: 'screwdriver-wrench', description: 'Home repairs, device fixes', iconSet: FontAwesome6 },
    { name: 'Fees', icon: 'price-tag', description: 'Bank fees, service charges', iconSet: Entypo },
    { name: 'Cleaning', icon: 'cleaning-services', description: 'Cleaning services, supplies', iconSet: MaterialIcons },
    { name: 'Stationery', icon: 'pencil', description: 'Notebooks, pens', iconSet: Entypo },
    { name: 'Snacks', icon: 'cake', description: 'Between-meal treats', iconSet: Entypo },
    { name: 'Donations', icon: 'hand', description: 'Charitable contributions', iconSet: Entypo },
    { name: 'Miscellaneous', icon: 'dots-three-horizontal', description: 'Other expenses', iconSet: Entypo },
    { name: 'Cash Withdrawal', icon: 'credit', description: 'ATM withdrawals', iconSet: Entypo },
  ];